### ISSUE TITLE
No Deletion of sensitive info (e.g. passwords) after use 

### ISSUE THREAD

**Issue by plumppapaya** [akamel001/Social-Wombat#11]
We should hash passwords and store that rather than passwords. Need to think about the default "Sys Admin" password. (How about calculating the hash of "Sys Admin" and hardcode that into the source code, this will be used only for the first time startup of the system. All future startups will see that some system file is on disk, and read that system file for the hashed current password.

**Comment by jtazin** [comment]
Not an issue according to grading comments.
